let
    Source = Web.BrowserContents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ2FpzCbz-qrjk-zq5E88hHmKrAB3b9VXQrEG4pu0rW5vCfVrm0Y7ljHiedHDorSb9gb75ilo_sOOjq/pubhtml#"),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "DIV[id='526005747'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)"}, {"Column2", "DIV[id='526005747'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)"}, {"Column3", "DIV[id='526005747'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)"}, {"Column4", "DIV[id='526005747'] > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)"}}, [RowSelector="DIV[id='526005747'] > DIV.ritz.grid-container > TABLE.waffle > * > TR"]),
    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Table From Html",{{"Column1", Int64.Type}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"}),
    #"Removed Top Rows" = Table.Skip(#"Removed Columns",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Promoted Headers", {{"Mes", type date}}, "es-AR"),
    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type with Locale", {{"Dólar Blue: Venta (ARS/USD)", type number}}, "en-US"),
    OriginalData = Table.TransformColumnTypes(#"Changed Type with Locale1", {{"Dólar Oficial Minorista: Venta (ARS/USD)", type number}}, "en-US"),
    #"Added Custom" = Table.AddColumn(OriginalData, "Custom", each OriginalData),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "ListaDolarBlue", each [Custom][#"Dólar Blue: Venta (ARS/USD)"]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "ListaDolarOficial", each [Custom][#"Dólar Oficial Minorista: Venta (ARS/USD)"]),
    #"Added Index" = Table.AddIndexColumn(#"Added Custom2", "Index", -2, 1, Int64.Type),
    #"Added Custom3" = Table.AddColumn(#"Added Index", "RangoListaDolarBlueM3", each if [Index] > -1 then List.Range([ListaDolarBlue], [Index], 3) else null),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "RangoListaDolarOficialM3", each if [Index] > -1 then List.Range([ListaDolarOficial], [Index], 3) else null),
    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Dólar Blue: Venta (ARS/USD) mm3m", each if [Index] > -1 then List.Average([RangoListaDolarBlueM3]) else null),
    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Dólar Oficial Minorista: Venta (ARS/USD) mm3m", each if [Index] > -1 then List.Average([RangoListaDolarOficialM3]) else null),
    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "RangoListaDolarBlueM12", each if [Index] > 8 then List.Range([ListaDolarBlue], [Index] - 9, 12) else null),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "RangoListaDolarOficialM12", each if [Index] > 8 then List.Range([ListaDolarOficial], [Index] - 9, 12) else null),
    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "Dólar Blue: Venta (ARS/USD) mm12m", each if [Index] > 8 then List.Average([RangoListaDolarBlueM12]) else null),
    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "Dólar Oficial Minorista: Venta mm12m", each if [Index] > 8 then List.Average([RangoListaDolarOficialM12]) else null),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom10",{"Custom", "ListaDolarBlue", "ListaDolarOficial", "Index", "RangoListaDolarBlueM3", "RangoListaDolarOficialM3", "RangoListaDolarBlueM12", "RangoListaDolarOficialM12"}),
    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Removed Columns1", {{"Dólar Blue: Venta (ARS/USD) mm3m", type number}, {"Dólar Oficial Minorista: Venta (ARS/USD) mm3m", type number}, {"Dólar Blue: Venta (ARS/USD) mm12m", type number}, {"Dólar Oficial Minorista: Venta mm12m", type number}}, "en-US")
in
    #"Changed Type with Locale2"