let
    Source = Excel.Workbook(Web.Contents("http://www.bcra.gov.ar/Pdfs/PublicacionesEstadisticas/ITCRMSerie.xls"), null, true),
    #"ITCRM y bilaterales1" = Source{[Name="ITCRM y bilaterales"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(#"ITCRM y bilaterales1",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}}, "en-US"),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers", {{"ITCRM ", type number}, {"ITCRB Brasil", type number}, {"ITCRB Canadá", type number}, {"ITCRB Chile", type number}, {"ITCRB Estados Unidos", type number}, {"ITCRB México", type number}, {"ITCRB Uruguay", type number}, {"ITCRB China", type number}, {"ITCRB India", type number}, {"ITCRB Japón", type number}, {"ITCRB Reino Unido", type number}, {"ITCRB Suiza", type number}, {"ITCRB Zona Euro", type number}, {"ITCRB Vietnam", type number}, {"ITCRB Sudamérica*", type number}}, "en-US"),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Column17", "Mes de referencia", "Column19"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "Período", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Período.1", "Período.2", "Período.3"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Período.1", type text}, {"Período.2", type text}, {"Período.3", type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each ([Período.2] <> null)),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows",".","",Replacer.ReplaceText,{"Período.2"}),
    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Período.1", "DD"}, {"Período.2", "MMnom"}, {"Período.3", "AA"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"AA", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type3", "AA__", each if [AA] > 90 then 1900 else 2000),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Conditional Column",{{"AA__", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type4", "AAAA", each [AA__] + [AA]),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom",{{"AAAA", Int64.Type}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type5", {"MMnom"}, FechaMesEng, {"MesTexto"}, "FechaMes", JoinKind.LeftOuter),
    #"Expanded FechaMes" = Table.ExpandTableColumn(#"Merged Queries", "FechaMes", {"MesNro"}, {"MM"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Expanded FechaMes",{{"DD", Int64.Type}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type6", "Fecha", each #date ( [AAAA], [MM], [DD] )),
    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom1",{{"Fecha", type date}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type7",{"DD", "MMnom", "AA", "AA__", "AAAA", "MM"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"Fecha", "ITCRM ", "ITCRB Brasil", "ITCRB Canadá", "ITCRB Chile", "ITCRB Estados Unidos", "ITCRB México", "ITCRB Uruguay", "ITCRB China", "ITCRB India", "ITCRB Japón", "ITCRB Reino Unido", "ITCRB Suiza", "ITCRB Zona Euro", "ITCRB Vietnam", "ITCRB Sudamérica*"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Reordered Columns", {"Fecha"}, "Attribute", "Value"),
    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Variable"}, {"Value", "ITCR"}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns1","*","",Replacer.ReplaceText,{"Variable"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","ITCRM ","ITCR Multilateral",Replacer.ReplaceText,{"Variable"})
in
    #"Replaced Value2"