let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs4vyaxKTM48vDlPITTYRUEjNzUlM1EhNzWvuDQxR1MpVge3msObyzJzFAyMgaqLU4uJUWtoBFcbCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Medida Cotizacion USD" = _t])
in
    Source