let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCihKTc7MVwgoys9NTQEyQoNdlGJ1sIoraICYiQq5hzeXZeYoGBgr5KYWpxZrEqne0AiuPhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Medida Precio USD" = _t])
in
    Source