let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCihKTc7MV3A5vDknsUjBKac0VSlWB13YPy0zOTMxRyk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Medida Tipo USD" = _t])
in
    Source