let
    Source = Excel.Workbook(File.Contents("E:\Users\agust\Desktop\Data.Driven Argentina\Productos\Geomarketing DDA\Bases de Datos\Google Mobility\Tablas Dim.xlsx"), null, true),
    TablaRef_Geo_Uru_Sheet = Source{[Item="TablaRef_Geo_Uru",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(TablaRef_Geo_Uru_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country_region_code", type text}, {"country_region", type text}, {"sub_region_1", type text}, {"sub_region_2", type text}, {"metro_area", type text}, {"iso_3166_2_code", type text}, {"place_id", type text}, {"Observaciones", type text}, {"Zona Geográfica", type text}})
in
    #"Changed Type"