let
    Source = Excel.Workbook(File.Contents("E:\Users\agust\Desktop\Data.Driven Argentina\Productos\Geomarketing DDA\Bases de Datos\Google Mobility\Cartografía\Argentina\Tablas Dim.xlsx"), null, true),
    #"Provincias Argentina_Sheet" = Source{[Item="Provincias Argentina",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Provincias Argentina_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country_region_code", type text}, {"country_region", type text}, {"sub_region_1", type text}, {"sub_region_2", type text}, {"metro_area", type text}, {"iso_3166_2_code", type text}, {"place_id", type text}, {"Observaciones", type text}, {"Tipo de Distrito", type text}, {"Provincia", type text}, {"Departamento", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column12"})
in
    #"Removed Columns"