let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8s0vy8zJTElMUdBISSzJV0jJTCzKzNdUitVBkctNBUoo5B7eDBRRMFdIObw2sRioKBYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Medida de Movilidad" = _t])
in
    Source